services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - ..:/workspace
      - ${HOME}/.ssh:/home/vscode/.ssh:cached
      - type: tmpfs
        target: /mnt/ramdisk
        tmpfs:
          size: 20971520
    command: tail -f /dev/null
    environment:
      - NATS_CONNECT_URL=nats-server:4222
    cap_add:
      - NET_ADMIN  
  setup:
    image: alpine
    command: >
      sh -c "apk add --no-cache openssl &&
             openssl req -new -newkey rsa:4096 -x509 -sha256 -days 9999 -nodes -out nats.crt -keyout nats.key -addext 'subjectAltName = DNS:localhost, DNS:nats' -subj '/CN=localhost' &&
             openssl req -x509 -newkey rsa:4096 -keyout /shared-data/key.pem -out /shared-data/cert.pem -days 365 -nodes -subj '/CN=example.com'"
    volumes:
      - shared-data:/shared-data

  nats-server:
    image: nats:latest
  nats-server-tls:
    image: nats:latest
    volumes:
        - shared-data:/shared-data
  nats-cluster-node-a:
    image: nats
    command: "--client_advertise nats-cluster-node-a --cluster_name TEST_CLUSTER --cluster nats://0.0.0.0:6222 "
  nats-cluster-node-b:
    image: nats
    command: "--client_advertise nats-cluster-node-b --cluster_name TEST_CLUSTER --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-cluster-node-a:6222"
    depends_on: ["nats-cluster-node-a"]
  nats-cluster-node-c:
    image: nats
    command: "--client_advertise nats-cluster-node-c --cluster_name TEST_CLUSTER --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-cluster-node-a:6222"
    depends_on: ["nats-cluster-node-a"]