
name: Auth tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64]
        nats-version: ['2.10.18']
        julia-num-threads: ['1']
        os: [ubuntu-latest]
    
    services:
      nats-no-tls:
        image: nats:${{ matrix.nats-version }}

    steps:
      - uses: actions/checkout@v2
      - name: "Start NATS server with token authentication."
        run: |
          echo $PWD
          name=`docker create --network ${{ job.container.network }} -p 4222:4222 -e GITHUB_ACTIONS=true -e CI=true nats:${{ matrix.nats-version }} --auth s3cr3t`
          docker container start $name
          sleep 2
          docker logs $name
      - name: "Start NATS server with basic authentication."
        run: |
          echo $PWD
          name=`docker create --network ${{ job.container.network }} -p 4223:4222 -e GITHUB_ACTIONS=true -e CI=true nats:${{ matrix.nats-version }} --user jakub --pass passw0rd`
          docker container start $name
          sleep 2
          docker logs $name
      - name: "Start NATS server with nkey authentication."
        run: |
          echo $PWD
          name=`docker create -v $(pwd)/test/configs/nats-server-nkey-auth.conf:/nats-server.conf --network ${{ job.container.network }} -p 4224:4222 -e GITHUB_ACTIONS=true -e CI=true nats:${{ matrix.nats-version }}`
          docker container start $name
          sleep 2
          docker logs $name
      - name: "Start NATS server with TLS authentication."
        run: |
          echo $PWD
          name=`docker create -v $(pwd)/test/certs:/certs -v $(pwd)/test/configs/nats-server-tls-auth.conf:/nats-server.conf --network ${{ job.container.network }} -p 4225:4222 -e GITHUB_ACTIONS=true -e CI=true nats:${{ matrix.nats-version }}`
          docker container start $name
          sleep 2
          docker logs $name
      # - name: "Start reply service"
      #   run: |
      #     docker ps
      #     name=`docker create --network ${{ job.container.network }} -e GITHUB_ACTIONS=true -e CI=true --entrypoint nats synadia/nats-box:latest --server nats://s3cr3t@nats:4222 reply help.please 'OK, I CAN HELP!!!'`
      #     container_id=`docker container start $name`
      #     sleep 2
      #     docker logs $container_id
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'
      - run: |
          JULIA_DEBUG=NATS JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} NATS_CONNECT_URL=localhost:4222 NATS_AUTH_TOKEN=s3cr3t julia --color=yes --code-coverage=user --project test/runtests.jl
      - run: |
          JULIA_DEBUG=NATS JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} NATS_CONNECT_URL=localhost:4223 NATS_USER=jakub NATS_PASS=passw0rd julia --color=yes --code-coverage=user --project test/runtests.jl
      - run: |
          JULIA_DEBUG=NATS JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} NATS_CONNECT_URL=jakub:passw0rd@localhost:4223 julia --color=yes --code-coverage=user --project test/runtests.jl
      - run: |
          JULIA_DEBUG=NATS JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} NATS_CONNECT_URL=localhost:4224 NATS_NKEY_SEED=SUADPKZWX3XJQO4GJEX2IGZAKCYUSLSLNJXFG7KPAYAODEVABRK6ZKKALA NATS_NKEY=UDBKUC5JFUX5SDF6CGBT3WAZEZSJTGMWWSCRJMODEUPVOKBPCLVODH2J julia --color=yes --code-coverage=user --project test/runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
        #   annotate: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Stop services"
        run: |
          docker kill $(docker ps -q )