name: Benchmarks

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        julia-version: ['1.9.3']
        julia-arch: [x64]
        nats-version: ['2.10.1']
        julia-num-threads: ['1', '1,1', '1,2'] # TODO: add ['1,4', '4,4'], but it require large runner, default there are only 2 cores. 
        os: [ubuntu-latest]
    
    
    # TODO: cannot enable jetstream this way, added "Start nats with jetstream step."
    services:
      nats:
        image: nats:${{ matrix.nats-version }}
        ports:
          - 4222:4222

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'
          JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} julia --project test/benchmarks.jl

