
name: Cluster tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64]
        nats-version: ['2.10.18']
        julia-num-threads: ['1']
        os: [ubuntu-latest]
    
    services:
      nats-no-tls:
        image: nats:${{ matrix.nats-version }}

    steps:
      - uses: actions/checkout@v2
      - name: "Start NATS cluster."
        run: |
          echo $PWD
          cd test/cluster
          docker compose up -d
          sleep 2
          docker ps
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'
          JULIA_DEBUG=NATS JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} julia --color=yes --code-coverage=user --project test/cluster.jl
      - uses: julia-actions/julia-processcoverage@v1
        #   annotate: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Stop services"
        run: |
          echo $PWD
          cd test/cluster
          docker compose down