name: JetStream tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64]
        nats-version: ['2.10.18']
        julia-num-threads: ['1'] # TODO: add ['1,4', '4,4'], but it require large runner, default there are only 2 cores. 
        os: [ubuntu-latest]
    
    services:
      nats-unused:
        image: nats:${{ matrix.nats-version }}

    steps:
      - name: "Start nats with jetstream"
        run: |
          docker network ls
          echo ${{ job.container.network }}
          name=`docker create --name nats --network ${{ job.container.network }} --network-alias nats -p 4222:4222 -e GITHUB_ACTIONS=true -e CI=true nats:2.10.1 --jetstream`
          docker container start $name
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'
          JULIA_DEBUG=NATS,JetStream JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} julia --color=yes --code-coverage=user --project test/jetstream.jl
      - uses: julia-actions/julia-processcoverage@v1
        #   annotate: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Stop services"
        run: |
          docker kill $(docker ps -q )
