name: Run tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        julia-version: ['1.9.3']
        julia-arch: [x64]
        nats-version: ['2.10.1']
        julia-num-threads: ['1'] # TODO: add ['1,4', '4,4'], but it require large runner, default there are only 2 cores. 
        os: [ubuntu-latest]
    
    
    # TODO: cannot enable jetstream this way, added "Start nats with jetstream step."
    services:
      nats-unused:
        image: nats:${{ matrix.nats-version }}
        # ports:
        #   - 4222:4222

    steps:
      - name: "Start nats with jetstream"
        run: |
          docker network ls
          echo ${{ job.container.network }}
          name=`docker create --name nats --network ${{ job.container.network }} --network-alias nats -p 4222:4222 -e GITHUB_ACTIONS=true -e CI=true nats:2.10.1 --jetstream`
          docker container start $name
      - name: "Start reply service"
        run: |
          docker ps
          name=`docker create --network ${{ job.container.network }} -e GITHUB_ACTIONS=true -e CI=true --entrypoint nats synadia/nats-box:latest --server nats:4222 reply help.please 'OK, I CAN HELP!!!'`
          container_id=`docker container start $name`
          sleep 2
          docker logs $container_id
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: ${{ matrix.julia-num-threads }}
      - uses: julia-actions/julia-processcoverage@v1
        #   annotate: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Stop services"
        run: |
          docker kill $(docker ps -q )
