
name: Secure connection tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        julia-version: ['1.9.3']
        julia-arch: [x64]
        nats-version: ['2.10.1']
        julia-num-threads: ['1'] # TODO: add ['1,4', '4,4'], but it require large runner, default there are only 2 cores. 
        os: [ubuntu-latest]
    
    services:
      nats-no-tls:
        image: nats:${{ matrix.nats-version }}
        options: --name nats

    steps:
      - uses: actions/checkout@v2
      - name: "Start TLS enabled NATS server."
        run: |
          echo $PWD
          name=`docker create -v $(pwd)/test/certs:/certs --network ${{ job.container.network }} --network-alias nats -p 4222:4222 -e GITHUB_ACTIONS=true -e CI=true nats:${{ matrix.nats-version }} --tls --tlscert /certs/nats.crt --tlskey /certs/nats.key`
          docker container start $name
          sleep 2
          docker logs $name
      # - uses: julia-actions/setup-julia@v1
      #   with:
      #     version: ${{ matrix.julia-version }}
      #     arch: ${{ matrix.julia-arch }}
      # - run: |
      #     julia --project -e 'using Pkg; Pkg.instantiate()'
      #     JULIA_NUM_THREADS=${{ matrix.julia-num-threads }} julia --color=yes --code-coverage=user --project test/chaos.jl
      # - uses: julia-actions/julia-processcoverage@v1
      #   #   annotate: true
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Stop services"
        run: |
          docker kill $(docker ps -q )